顔を隠す写真をユーザーが任意の写真をアップロードできるようにする
illionillion/face-stamp-app-prototype pull request #3
Opened 2023-12-25 11:23 UTC by SEKI-YUTA

後でコードをキレイにする
実現したい動きとしては一応できている

2023-12-27 13:00 UTC, SEKI-YUTA commented on src/App.tsx
> +import { FaImage } from "react-icons/fa";
ボタンの横にアイコンをつけるためにimport
ボタンの箇所にも書いているが、同じようなボタンでわかりにくいためアイコンをつけた

2023-12-27 13:02 UTC, SEKI-YUTA commented on src/App.tsx
> +        let stamp = null;
顔を隠す用の画像が選択されていればその画像を使い、なければiconListに入っている物を使用する

2023-12-27 13:03 UTC, SEKI-YUTA commented on src/App.tsx
> +          <FaRegSmileWink />顔を隠す写真を選択
同じようなボタンでややこしいのでアイコンをつけた

2023-12-27 13:03 UTC, SEKI-YUTA commented on src/App.tsx
> +          <FaImage/>顔が写った画像を選択
同じようなボタンでややこしいのでアイコンをつけた

2023-12-27 14:55 UTC, illionillion requested changes
確かに、このボタン押したら顔のスタンプの代わりの画像入れられるっていうのは初見だと分かりにくいかも

将来的には、設定できるスタンプの数とか種類を今回のPR内容みたいにカスタマイズできたら良いなとは思ってる

レビューの修正終わったらマージしようと思います！！

2023-12-27 14:55 UTC, illionillion commented on src/App.tsx
> +            <Img src={faceCoverImage.src} width='100px' height='100px' />
`objectFit="contain"`これつけて画像が崩れて表示されないようにしてほしいです

2023-12-27 14:55 UTC, illionillion commented on src/App.tsx
> +        {
こっちの方が綺麗かも

```tsx
        {
          faceCoverImage !== undefined &&
          <Container width='100%' display='flex' flexDirection='row' justifyContent='end'>
            <Text>右の写真で顔が隠されます。</Text>
            <Img src={faceCoverImage.src} width='100px' height='100px' objectFit="contain" />
          </Container>
        }
```

2023-12-27 14:55 UTC, illionillion commented on src/App.tsx
> +          <FaRegSmileWink />顔を隠す写真を選択
`leftIcon`で左側のアイコン指定できるよー

```tsx
<FileButton
  isLoading={isFaceCoverImageUploading}
  accept='image/*'
  onChange={handleFaceCoverImage}
  leftIcon={<FaRegSmileWink />}
>
  顔を隠す写真を選択
</FileButton>
```

2023-12-27 14:55 UTC, illionillion commented on src/App.tsx
> +          <FaImage/>顔が写った画像を選択
ここも同じく`leftIcon`で指定できるー

2023-12-28 03:27 UTC, SEKI-YUTA commented on src/App.tsx
> +            <Img src={faceCoverImage.src} width='100px' height='100px' />
実際に顔を隠す時に使われるのはobjectFit="contain"がつけていない時の状態なのであえてつけてない

2023-12-28 03:30 UTC, SEKI-YUTA commented on src/App.tsx
> +        {
そういえばこんな書き方もできた

2023-12-28 12:09 UTC, illionillion approved these changes

2023-12-28 12:09 UTC, merged